# Generated by Django 4.2.7 on 2023-11-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
    ]
